"""empty message

Revision ID: 28df68d9d6c8
Revises: 
Create Date: 2022-01-06 20:16:02.157168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28df68d9d6c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=64), nullable=True),
    sa.Column('modelo', sa.String(length=64), nullable=True),
    sa.Column('fabricante', sa.String(length=64), nullable=True),
    sa.Column('renavan', sa.String(length=64), nullable=True),
    sa.Column('combustivel', sa.String(length=64), nullable=True),
    sa.Column('lotacao', sa.String(length=64), nullable=True),
    sa.Column('anofabricacao', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa'),
    sa.UniqueConstraint('renavan')
    )
    op.create_table('maintenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orcamento_id', sa.String(length=64), nullable=True),
    sa.Column('tipo_manutencao', sa.String(length=64), nullable=True),
    sa.Column('descricao', sa.String(length=128), nullable=True),
    sa.Column('quant_itens', sa.Integer(), nullable=True),
    sa.Column('valor_unit', sa.Integer(), nullable=True),
    sa.Column('valor_final', sa.Integer(), nullable=True),
    sa.Column('hodometro', sa.Integer(), nullable=True),
    sa.Column('tabela_fipe', sa.String(length=64), nullable=True),
    sa.Column('veiculo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['veiculo'], ['vehicles.placa'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('orcamento_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance')
    op.drop_table('vehicles')
    op.drop_table('users')
    # ### end Alembic commands ###
