"""empty message

Revision ID: 51d238ea9688
Revises: cbb18e2b3bdb
Create Date: 2021-12-21 22:04:34.927856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51d238ea9688'
down_revision = 'cbb18e2b3bdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('anofabricacao', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'anofabricacao')
    # ### end Alembic commands ###
