"""empty message

Revision ID: cbb18e2b3bdb
Revises: 
Create Date: 2021-12-17 01:00:03.421575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbb18e2b3bdb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=64), nullable=True),
    sa.Column('modelo', sa.String(length=64), nullable=True),
    sa.Column('fabricante', sa.String(length=64), nullable=True),
    sa.Column('renavan', sa.String(length=64), nullable=True),
    sa.Column('combustivel', sa.String(length=64), nullable=True),
    sa.Column('lotacao', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa'),
    sa.UniqueConstraint('renavan')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles')
    op.drop_table('users')
    # ### end Alembic commands ###
